"""Initial migration with Spotify metadata fields

Revision ID: 8ca7941bd9c4
Revises:
Create Date: 2025-10-18 10:38:39.676261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca7941bd9c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('cover_art_url', sa.String(length=500), nullable=True))
    op.alter_column('musicitem', 'tracks',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text('("[]")'))
    op.alter_column('musicitem', 'album_genres',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text('("[]")'))
    op.alter_column('musicitem', 'album_cover_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('musicitem', 'musicbrainz_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('musicitem', 'musicbrainz_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('musicitem', 'album_cover_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('musicitem', 'album_genres',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('("[]")'))
    op.alter_column('musicitem', 'tracks',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('("[]")'))
    op.drop_column('album', 'cover_art_url')
    # ### end Alembic commands ###